version: '3.8'

services:
  app:
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host  # Use host network mode to access X server
